spring:
  application:
    name: maejang

  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_USERNAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update   # 처음엔 update, 나중에 validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # dialect는 MySQL에서 자동 감지 (경고 제거)

JWT_SECRET: vBnEVhqZXHCoIbVr2VhCNzmLmZqz5TNa